Resources:
  af2batchcdk:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/lambda_1/lambda_function.lambda_handler
      CodeUri: /Users/twuam/Desktop/AWSome Builder/2&3/af2-batch-cdk
      Runtime: python3.9
      Environment:
        Variables: {}
